const events = [
  {
    id: 1,
    name: "New Lecturers Meeting",
    price: 2200,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 10, month: "Nov" },
    image: "./images/meeting-01.jpg",
    upcomming: true,
    category: "none",
  },
  {
    id: 2,
    name: "Online Teaching Techniques",
    price: 2200,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 14, month: "Nov" },
    image: "./images/meeting-02.jpg",
    upcomming: true,
    category: "none",
  },
  {
    id: 3,
    name: "Higher Education Conference",
    price: 1400,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 26, month: "Nov" },
    image: "./images/meeting-03.jpg",
    upcomming: true,
    category: "none",
  },
  {
    id: 4,
    name: "Student Training Meetup",
    price: 3000,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 26, month: "Nov" },
    image: "./images/meeting-04.jpg",
    upcomming: true,
    category: "none",
  },
  {
    id: 5,
    name: "New Lecturers Meeting",
    price: 1400,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 12, month: "Nov" },
    image: "./images/meeting-01.jpg",
    upcomming: false,
    category: ["SOON"],
  },
  {
    id: 6,
    name: "Online Teaching Techniques",
    price: 3600,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 14, month: "Nov" },
    image: "./images/meeting-02.jpg",
    upcomming: false,
    category: ["IMPORTANT"],
  },
  {
    id: 7,
    name: "Network Teaching Concept",
    price: 2400,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 16, month: "Nov" },
    image: "./images/meeting-03.jpg",
    upcomming: false,
    category: ["SOON"],
  },
  {
    id: 8,
    name: "Online Teaching Tools",
    price: 3200,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 18, month: "Nov" },
    image: "../images/meeting-04.jpg",
    upcomming: false,
    category: ["ATTRACTIVE"],
  },
  {
    id: 9,
    name: "Online Teaching Technique",
    price: 3400,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 22, month: "Nov" },
    image: "./images/meeting-02.jpg",
    upcomming: false,
    category: ["ATTRACTIVE"],
  },
  {
    id: 10,
    name: "Technology Conference",
    price: 4600,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 24, month: "Nov" },
    image: "./images/meeting-03.jpg",
    upcomming: false,
    category: ["IMPORTANT"],
  },
  {
    id: 11,
    name: "Online Teaching Techniques",
    price: 5200,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 27, month: "Nov" },
    image: "./images/meeting-01.jpg",
    upcomming: false,
    category: ["IMPORTANT", "ATTRACTIVE"],
  },
  {
    id: 12,
    name: "Instant Lecture Design",
    price: 6400,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 28, month: "Nov" },
    image: "./images/meeting-02.jpg",
    upcomming: false,
    category: ["SOON", "IMPORTANT"],
  },
  {
    id: 13,
    name: "Online Social Networking",
    price: 7400,
    description: "Morbi in libero blandit lectus cursus ullamcorper.",
    date: { day: 30, month: "Nov" },
    image: "./images/meeting-04.jpg",
    upcomming: false,
    category: ["SOON", "ATTRACTIVE"],
  },
];

export { events };
